dist: bionic
language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
addons:
  apt:
    packages:
      - libgconf-2-4
      - xvfb
      - libxtst6
      - libnss3
      - libgtk-3-0
      - libxss1
      - libasound2
  chrome: stable
cache:
  directories:
    - ~/.cache
env:
  - NODE_ENV=test
install:
  - npm install -g @sherlog/cli && yarn install
script:
  - node ./node_modules/browserslist/cli.js
  - yarn run lint
  - yarn run test:e2e:chrome
