dist: bionic
language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
addons:
  apt:
    packages:
      - libgconf-2-4
  chrome: stable
install:
  - yarn install
script:
  - yarn run lint
  - yarn run test:e2e:chrome
